name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Hub Login
      run: |
        echo "Login into the docker hub"
          docker login -u ${{secrets.DOCKER_HUB_USERNAME }} ${{ secrets.DOCKER_HUB_PASSWD }}
        
    - name: Build Docker All Images
      id: build-all-docker-images
      run: |
       echo "Building Docker images ==> "
       docker-compose build
       
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # - name: Docker Compose Run Action
    #   # You may pin to the exact commit or the version.
    #   # uses: adrielcodeco/docker-compose-run-action@279848890d86008050ed55bba6a8cffad6668a3f
    #   uses: adrielcodeco/docker-compose-run-action@v1
    #   with:
    #     # relative path to compose file(s)
    #     # compose-file: # optional, default is ./docker-compose.yml
    #     # additional options to pass to `docker-compose` command
    #     # compose-flags: # optional, default is 
    #     # service to perform docker-compose run
    #     service: "discovery-service"
    #     # command to pass to `docker-compose run`
    #     # command: # optional
    #     # additional options to pass to `docker-compose run` command
    #     # run-flags: # optional, default is 

    - name: List all built docker images
      run: |
        docker images | grep kageja

    - name: Push all of docker images
      run: |
        docker-compose push
              
